In [2]:
import nltk
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [3]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\park\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [4]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\park\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [6]:
tokens = nltk.word_tokenize("Hello World!, This is a dog.")

words = [word for word in tokens if word.isalpha()]
print(words)

['Hello', 'World', 'This', 'is', 'a', 'dog']


In [8]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\park\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [10]:
from nltk.corpus import stopwords
print(stopwords.words('english')[:20])

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his']


In [12]:
text = 'This is a dog.'
print(nltk.word_tokenize(text))

['This', 'is', 'a', 'dog', '.']


In [13]:
text = 'This is a house. This is a dog.'
print(nltk.sent_tokenize(text))

['This is a house.', 'This is a dog.']


In [14]:
from tensorflow.keras.preprocessing.text import *
print(text_to_word_sequence("This is a dog."))

['this', 'is', 'a', 'dog']


In [15]:
import numpy as np
from keras.utils import to_categorical

text =["cat", "dog", "cat", "bird"]

total_pets=["cat", "dog", "turtle", "fish", "bird"]
print("text=", text)

text= ['cat', 'dog', 'cat', 'bird']


In [17]:
mapping = {}
for x in range(len(total_pets)):
    mapping[total_pets[x]] = x
print(mapping)

for x in range(len(text)):
    text[x] = mapping[text[x]]
print("text=", text)

one_hot_encode = to_categorical(text)
print("text=", one_hot_encode)

{'cat': 0, 'dog': 1, 'turtle': 2, 'fish': 3, 'bird': 4}
text= [0, 1, 0, 4]
text= [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
from tensorflow.keras.preprocessing.text import Tokenizer

t = Tokenizer()
text = """Deep learning is part of a broader family of machine learning methods based on artificial neural networks with representation learning."""

t.fit_on_texts([text])
print("단어집합 : ", t.word_index)

단어집합 :  {'learning': 1, 'of': 2, 'deep': 3, 'is': 4, 'part': 5, 'a': 6, 'broader': 7, 'family': 8, 'machine': 9, 'methods': 10, 'based': 11, 'on': 12, 'artificial': 13, 'neural': 14, 'networks': 15, 'with': 16, 'representation': 17}


In [19]:
seq = t.texts_to_sequences([text])[0]
print(text,"->", seq)

Deep learning is part of a broader family of machine learning methods based on artificial neural networks with representation learning. -> [3, 1, 4, 5, 2, 6, 7, 8, 2, 9, 1, 10, 11, 12, 13, 14, 15, 16, 17, 1]


In [20]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

X = pad_sequences([[7,8,9], [1,2,3,4,5], [7]], maxlen=3, padding='pre')
print(X)

[[7 8 9]
 [3 4 5]
 [0 0 7]]


In [22]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential

model = Sequential()
model.add(Embedding(100, 4, input_length=3))

input_array = np.random.randint(100, size=(32, 3))
model.compile('rmsprop', 'mse')
output_array = model.predict(input_array)
print(output_array.shape)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step
(32, 3, 4)


In [23]:
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

docs = [  'additional income',
  'best price',
  'big bucks',
  'cash bonus',
  'earn extra cash',
  'spring savings certificate',
  'valero gas marketing',
  'all domestic employees',
  'nominations for oct',
  'confirmation from spinner']

labels = np.array([1,1,1,1,1,0,0,0,0,0])
vocab_size = 50
encode_docs = [one_hot(d, vocab_size) for d in docs]
print(encode_docs)

max_length = 4
padded_docs = pad_sequences(encode_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[25, 19], [12, 10], [29, 43], [42, 23], [47, 31, 42], [6, 20, 10], [30, 48, 30], [49, 5, 44], [37, 3, 43], [28, 5, 38]]
[[25 19  0  0]
 [12 10  0  0]
 [29 43  0  0]
 [42 23  0  0]
 [47 31 42  0]
 [ 6 20 10  0]
 [30 48 30  0]
 [49  5 44  0]
 [37  3 43  0]
 [28  5 38  0]]


In [24]:
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_docs, labels, epochs=50, verbose=0)

loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('정확도=', accuracy)

c:\Users\park\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


정확도= 1.0


In [25]:
test_doc = ['big income']
encode_docs = [one_hot(d, vocab_size) for d in test_doc]
padded_docs = pad_sequences(encode_docs, maxlen=max_length, padding='post')
print(model.predict(padded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
[[0.57564825]]


In [26]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, LSTM
from tensorflow.keras.preprocessing.text import Tokenizer

In [27]:
text_data = """Soft as the voice of an angel
Breathing a lesson unhead
Hope with a gentle persuasion
Whispers her comforting word
Wait till the darkness is over
Wait till the tempest is done
Hope for sunshine tomorrow
After the shower
"""

tokenizer = Tokenizer()
tokenizer.fit_on_texts([text_data])
encoded = tokenizer.texts_to_sequences([text_data])[0]
vocab_size = len(tokenizer.word_index) + 1
print('Vocabulary size:', vocab_size)

Vocabulary size: 32


In [28]:
print(tokenizer.word_index)
vocab_size = len(tokenizer.word_index) + 1
print('어휘 크기: %d' % vocab_size)

{'the': 1, 'a': 2, 'hope': 3, 'wait': 4, 'till': 5, 'is': 6, 'soft': 7, 'as': 8, 'voice': 9, 'of': 10, 'an': 11, 'angel': 12, 'breathing': 13, 'lesson': 14, 'unhead': 15, 'with': 16, 'gentle': 17, 'persuasion': 18, 'whispers': 19, 'her': 20, 'comforting': 21, 'word': 22, 'darkness': 23, 'over': 24, 'tempest': 25, 'done': 26, 'for': 27, 'sunshine': 28, 'tomorrow': 29, 'after': 30, 'shower': 31}
어휘 크기: 32


In [29]:
sequences = list()
for i in range(1, len(encoded)):
    sequence = encoded[i-1:i+1]
    sequences.append(sequence)
print(sequences)
print("총 시퀀스 개수: %d" %len(sequences))

[[7, 8], [8, 1], [1, 9], [9, 10], [10, 11], [11, 12], [12, 13], [13, 2], [2, 14], [14, 15], [15, 3], [3, 16], [16, 2], [2, 17], [17, 18], [18, 19], [19, 20], [20, 21], [21, 22], [22, 4], [4, 5], [5, 1], [1, 23], [23, 6], [6, 24], [24, 4], [4, 5], [5, 1], [1, 25], [25, 6], [6, 26], [26, 3], [3, 27], [27, 28], [28, 29], [29, 30], [30, 1], [1, 31]]
총 시퀀스 개수: 38


In [30]:
sequences = np.array(sequences)
X, y = sequences[:,0],sequences[:,1]
print("X=", X)
print("y=", y)
X = X.reshape((X.shape[0], 1)) # (samples, timesteps)

X= [ 7  8  1  9 10 11 12 13  2 14 15  3 16  2 17 18 19 20 21 22  4  5  1 23
  6 24  4  5  1 25  6 26  3 27 28 29 30  1]
y= [ 8  1  9 10 11 12 13  2 14 15  3 16  2 17 18 19 20 21 22  4  5  1 23  6
 24  4  5  1 25  6 26  3 27 28 29 30  1 31]


In [31]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN, LSTM
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=1))
model.add(LSTM(50))
model.add(Dense(vocab_size, activation='softmax'))

c:\Users\park\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [33]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=500, verbose=2)

Epoch 1/500
2/2 - 3s - 1s/step - accuracy: 0.0526 - loss: 3.4654
Epoch 2/500
2/2 - 0s - 21ms/step - accuracy: 0.0526 - loss: 3.4640
Epoch 3/500
2/2 - 0s - 17ms/step - accuracy: 0.1053 - loss: 3.4629
Epoch 4/500
2/2 - 0s - 19ms/step - accuracy: 0.1053 - loss: 3.4620
Epoch 5/500
2/2 - 0s - 19ms/step - accuracy: 0.1316 - loss: 3.4611
Epoch 6/500
2/2 - 0s - 18ms/step - accuracy: 0.1316 - loss: 3.4602
Epoch 7/500
2/2 - 0s - 19ms/step - accuracy: 0.1053 - loss: 3.4592
Epoch 8/500
2/2 - 0s - 20ms/step - accuracy: 0.1053 - loss: 3.4583
Epoch 9/500
2/2 - 0s - 19ms/step - accuracy: 0.1316 - loss: 3.4573
Epoch 10/500
2/2 - 0s - 19ms/step - accuracy: 0.1316 - loss: 3.4564
Epoch 11/500
2/2 - 0s - 18ms/step - accuracy: 0.1053 - loss: 3.4554
Epoch 12/500
2/2 - 0s - 19ms/step - accuracy: 0.1053 - loss: 3.4545
Epoch 13/500
2/2 - 0s - 18ms/step - accuracy: 0.1053 - loss: 3.4535
Epoch 14/500
2/2 - 0s - 19ms/step - accuracy: 0.1053 - loss: 3.4525
Epoch 15/500
2/2 - 0s - 21ms/step - accuracy: 0.1053 - loss

In [34]:
test_text = 'Wait'
encoded = tokenizer.texts_to_sequences([test_text])[0]
encoded = np.array(encoded)

onehot_output = model.predict(encoded)
print('onehot_output=', onehot_output)

output = np.argmax(onehot_output)
print('output=', output)

print(test_text, '=>', end=" ")
for word, index in tokenizer.word_index.items():
    if index == output:
        print(word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 239ms/step
onehot_output= [[7.36915445e-06 7.00298688e-06 1.53486508e-05 1.04216114e-02
  1.26552541e-05 9.55927372e-01 7.99397193e-03 9.75384319e-06
  9.65303207e-06 8.27818781e-07 1.30984072e-05 6.44386892e-05
  9.35444259e-04 3.74288248e-07 1.12083595e-04 4.58764378e-03
  3.68224178e-03 1.34062342e-04 1.97084737e-05 8.87938222e-06
  1.02774817e-02 1.53416069e-04 2.29545531e-05 6.02542286e-07
  6.36689492e-07 8.03355476e-07 8.74119110e-07 4.31994256e-03
  1.14021148e-03 6.11164724e-05 5.76256862e-05 7.81678921e-07]]
output= 5
Wait => till


In [35]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
imdb = keras.datasets.imdb
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=10000)
print(x_train[0])

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 3s 0us/step
[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]


In [37]:
word_to_index = imdb.get_word_index()
word_to_index = {k:(v+3) for k,v in word_to_index.items()}
word_to_index["<PAD>"] = 0
word_to_index["<START>"] = 1
word_to_index["<UNK>"] = 2
word_to_index["<UNUSED>"] = 3

index_to_word = dict([(value, key) for (key, value) in word_to_index.items()])
print(' '.join([index_to_word[index] for index in x_train[0]]))

<START> this film was just brilliant casting location scenery story direction everyone's really suited the part they played and you could just imagine being there robert <UNK> is an amazing actor and now the same being director <UNK> father came from the same scottish island as myself so i loved the fact there was a real connection with this film the witty remarks throughout the film were great it was just brilliant so much that i bought the film as soon as it was released for <UNK> and would recommend it to everyone to watch and the fly fishing was amazing really cried at the end it was so sad and you know what they say if you cry at a film it must have been good and this definitely was also <UNK> to the two little boy's that played the <UNK> of norman and paul they were just brilliant children are often left out of the <UNK> list i think because the stars that play them all grown up are such a big profile for the whole film but these children are amazing and should be praised for wha

In [38]:
from tensorflow.keras.layers import *

x_train = pad_sequences(x_train, maxlen=100)
x_test = pad_sequences(x_test, maxlen=100)

vocab_size = 10000

model = Sequential()
model.add(Embedding(vocab_size, 64, input_length=100))
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

model.summary()

c:\Users\park\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [39]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(x_train, y_train, batch_size=64, epochs=20, verbose=1, validation_data=(x_test,y_test))

Epoch 1/20
391/391 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.6751 - loss: 0.5723 - val_accuracy: 0.8536 - val_loss: 0.3347
Epoch 2/20
391/391 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.9354 - loss: 0.1851 - val_accuracy: 0.8319 - val_loss: 0.4086
Epoch 3/20
391/391 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.9925 - loss: 0.0329 - val_accuracy: 0.8318 - val_loss: 0.5173
Epoch 4/20
391/391 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.9993 - loss: 0.0064 - val_accuracy: 0.8366 - val_loss: 0.6078
Epoch 5/20
391/391 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.9997 - loss: 0.0023 - val_accuracy: 0.8378 - val_loss: 0.6687
Epoch 6/20
391/391 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 1.0000 - loss: 8.9582e-04 - val_accuracy: 0.8412 - val_loss: 0.6994
Epoch 7/20
391/391 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 1.0000 - loss: 4.9559e-04 - val_accuracy: 0.8397 - val_loss: 0.7263
Epoch 8/20
391/391 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 1.0000 - loss: 4.6267e-04 - val_

In [40]:
results = model.evaluate(x_test, y_test, verbose=2)
print(results)

782/782 - 1s - 2ms/step - accuracy: 0.8184 - loss: 1.1433
[1.143337607383728, 0.8184000253677368]


In [41]:
review = "What can I say about this movie that was already said? It is my favorite time travel sci-fi, adventure epic comedy in the 80's and I love this movie to death! When I saw this movie I was thrown out by its theme. An excellent sci-fi, adventure epic, I LOVE the 80s. It's simple the greatest time travel movie ever happened in the history of world cinema. I love this movie to death, I love, LOVE, love it!"
import re
review = re.sub("[^0-9a-zA-Z ]", "", review).lower()
review_encoding = []
# 리뷰의 각 단어 대하여 반복한다.
for w in review.split():
    index = word_to_index.get(w, 2) # 딕셔너리에 없으면 2 반환
    if index <= 10000: # 단어의 개수는 10000이하
        review_encoding.append(index)
    else:
        review_encoding.append(word_to_index["UNK"])
# 2차원 리스트로 전달하여야 한다.
test_input = pad_sequences([review_encoding], maxlen = 100)
value = model.predict(test_input) # 예측
if(value > 0.5):
    print("긍정적인 리뷰입니다.")
else:
    print("부정적인 리뷰입니다.")















































































1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
긍정적인 리뷰입니다.
